Cypress.Commands.add('startProcess',(projectSelect, amount, creditMaturity)=>{
  cy.get('#projectSelect').select(projectSelect).should('have.class', 'ng-valid')
  cy.get('#amount').select(amount).should('have.class', 'ng-valid')
  cy.get('#creditMaturity').select(creditMaturity).should('have.class', 'ng-valid')
})
Cypress.Commands.add('typeLogin', (email) => {
    cy.get('#email-input').type(email).should('have.class', 'ng-valid')
    })
Cypress.Commands.add('familyStatus',(maritalStatus,childNumberPropal) =>{
  cy.get('#maritalStatus-input').select(maritalStatus).should('have.class', 'ng-valid')
  cy.get('#childNumberPropal-input').select(childNumberPropal).should('have.class', 'ng-valid')
})
Cypress.Commands.add('housingStatutUser', (housingStatus, housingStatusMonth, housingStatusYear) =>{
  cy.get('#housingStatus-input').select(housingStatus).should('have.class', 'ng-valid')
  cy.get('#housingStatusFrom-input-month').type(housingStatusMonth).should('have.class', 'ng-valid')
  cy.get('#housingStatusFrom-input-year').type(housingStatusYear).should('have.class', 'ng-valid')
})
Cypress.Commands.add('activityUser',(activitySector,profession, businessActivityMonth,businessActivityYear) =>{
  cy.get('#activitySector-input').select(activitySector).should('have.class', 'ng-valid')
  cy.get('#profession-input').select(profession).should('have.class', 'ng-valid')
  cy.get('#businessActivityStartDate-input-month').type(businessActivityMonth).should('have.class', 'ng-valid')
  cy.get('#businessActivityStartDate-input-year').type(businessActivityYear).should('have.class', 'ng-valid')
})
Cypress.Commands.add('salaryUser',(mainIncome, housingAssistance, additionalIncome) =>{
  cy.get('#mainIncome-input').type(mainIncome).should('have.class', 'ng-valid')
  cy.get('#housingAssistance-input').type(housingAssistance).should('have.class', 'ng-valid')
  cy.get('#additionalIncome-input').type(additionalIncome).should('have.class', 'ng-valid')
})
Cypress.Commands.add('outcomesUser',(rentAmount, loanCount, type, loanAmount) =>{
  cy.get('#rentAmount-input').type(rentAmount).should('have.class', 'ng-valid')
  cy.get('#loanCount-input').select(loanCount).should('have.class', 'ng-valid')
  cy.get('#type-input').select(type).should('have.class', 'ng-valid')
  cy.get('#loanAmount-input').type(loanAmount).should('have.class', 'ng-valid')
})
Cypress.Commands.add('bankUser', (bankCode, bankFrom)=>{
  cy.get('#bankCode-input').select(bankCode).should('have.class', 'ng-valid')
  cy.get('#bankFrom-input-year').type(bankFrom).should('have.class', 'ng-valid')
})
Cypress.Commands.add('personnalInfo',(gender, lastName, firstName,dayBirth,monthBirth,yearBirth,postalCodeBirth,cityBirth)=>{
  cy.get(gender).check({ force: true }).should('be.checked')
  cy.get('#lastName-input').type(lastName).should('have.class', 'ng-valid')
  cy.get('#firstName-input').type(firstName).should('have.class', 'ng-valid')
  cy.get('#dateOfBirth-input-day').type(dayBirth).should('have.class', 'ng-valid')
  cy.get('#dateOfBirth-input-month').type(monthBirth).should('have.class', 'ng-valid')
  cy.get('#dateOfBirth-input-year').type(yearBirth).should('have.class', 'ng-valid')
  cy.get('#postalCode-input').type(postalCodeBirth).should('have.class', 'ng-valid')
  cy.get('#city-input').should('have.class', 'ng-valid')
  cy.wait(2000)
})
Cypress.Commands.add('userContact',(personnalNumber, userAddress, userPostalCode, userCountry)=>{
  cy.get('#cellPhoneNumber-input').type(personnalNumber).should('have.class', 'ng-valid')
  cy.get('#address-input').type(userAddress).should('have.class', 'ng-valid')
  cy.get('#postalCode-input').type(userPostalCode).should('have.class', 'ng-valid')
  cy.get('#city-input').should('have.class', 'ng-valid')
  cy.get('#countryZone-input').select(userCountry).should('have.class', 'ng-valid')
})