context('Choose the options to get credit with profile 2', () => {
 let profile2 = require('../fixtures/Profile2married')
  before(() => {
    cy.visit("https://www.younited-credit.com/")
    cy.wait(2000)
  })
    it('Start process on LandingPage',()=>{
      cy.title().should('include','Le Crédit')
      cy.startProcess(profile2.projectSelect, profile2.amount, profile2.creditMaturity)
      cy.get('[data-di-id=di-id-bca9a80c-4fc29f73]').click()
    })
   it('Enter email', ()=>{
    cy.url().should('include', '/email')
    cy.get("h2").should('contain', 'Découvrez votre offre de prêt de')
    cy.typeLogin(profile2.email)
    cy.get('[data-test=navigator-compact-forward]').click()

   })
  it('Consummer choose his marital statut',() => {
    cy.url().should('contain','familysituation')
    cy.get("h2").should('contain', 'Votre situation familiale')
    cy.familyStatus(profile2.maritalStatus, profile2.childNumberPropal)
    cy.get('[type="checkbox"]').check({ force: true }).should('be.checked') 
    cy.get('[data-test=navigator-compact-forward]').click()
  })
  it('Consumer choose is housing statut',()=>{
    cy.url().should('include', '/housing')
    cy.get("h2").should('contain', 'Votre logement')
    cy.housingStatutUser(profile2.housingStatus, profile2.housingStatusMonth,profile2.housingStatusYear)
    cy.get('[type="checkbox"]').uncheck({ force: true })
    cy.get('[data-test=navigator-compact-forward]').click()     
  })
  it('Consumer choose his job',()=>{
    cy.get("h2").should('contain', 'Votre situation professionnelle')
    cy.url().should('include', '/professionalsituation')
    cy.activityUser(profile2.activitySector,profile2.profession,profile2.contractType,profile2.employedFromMonth,profile2.employedFromeYear)
    cy.get('[data-test=navigator-compact-forward]').click()
  })
  it('Consumer choose his partner job',()=>{
    cy.url().should('include', '/partnerprofession')
    cy.get("h2").should('contain', 'Profession de votre conjoint')
    cy.partnerActivity(profile2.partnerActivitySector,profile2.partnerProfession,profile2.partnerContract,profile2.partnerEmployedM,profile2.partnerEmployedY)
    cy.get('[data-test=navigator-compact-forward]').click()
  })   
  it('Consumer give his salary',()=>{
    cy.url().should('include', '/incomes')
    cy.get("h2").should('contain', 'Vos revenus mensuels')
    cy.salaryUser(profile2.mainIncome, profile2.coIncome, profile2.housingAssistance, profile2.additionalIncome,profile2.maritalStatus)
    cy.get('[data-test=navigator-compact-forward]').click()
  })  
  it('Consumer give his outcomes',()=>{
    cy.url().should('include', '/outcomes')
    cy.get("h2").should('contain', 'Vos charges mensuelles')
    cy.outcomeUser(profile2.mortgageAmount,profile2.rentAmount,profile2.loanCount,profile2.type,profile2.loanAmount,profile2.maritalStatus)
    cy.get('[data-test=navigator-compact-forward]').click()  
  })    
  it('Consumer give his bank', ()=>{
    cy.url().should('include', '/bank')
    cy.get("h2").should('contain', 'Votre banque')
    cy.bankUser(profile2.bankCode, profile2.bankFrom)
    cy.get('[data-test=navigator-compact-forward]').click()
  })
  it('Consumer give personnal info',()=>{
    cy.get("h2").should('contain','Vos informations')
    cy.url().should('contain','/identity')
    cy.personnalInfo(profile2.maritalStatus, profile2.gender,profile2.lastName,profile2.firstName, null, profile2.dayBirth,profile2.monthBirth,profile2.yearBirth,profile2.postalCodeBirth)
    cy.get('[data-test=navigator-compact-forward]').click()
  })
  it('Consumer give Partner personnal info',()=>{
    cy.get("h2").should('contain','Les informations de votre conjoint')
    cy.url().should('contain','/partneridentity')
    cy.personnalInfo(profile2.maritalStatus,profile2.genderPartner,profile2.lastNamePartner,profile2.firstNamePartner, profile2.maidenName, profile2.dayBirthPartner,profile2.monthBirthPartner,profile2.yearBirthPartner,profile2.postalCodeBirthPartner)
    cy.get('[data-test=navigator-compact-forward]').click()
  })
  it('Consumer give his contact',()=>{
    cy.get("h2").should('contain','Vos coordonnées')
    cy.url().should('contain','/contact')
    cy.userContact(profile2.personnalNumber,profile2.userAddress,profile2.userPostalCode,profile2.userCountry)
    cy.get('[data-test=navigator-compact-forward]').click()
  })   
})