context('Choose the options to get credit with profile 1', () => {
  before(() => {
    cy.visit("https://www.younited-credit.com/")
    cy.wait(2000)
    cy.title().should('include','Le Crédit')
    cy.get('#projectSelect').select('NEWCAR')
    cy.get('option').should('contain','Véhicule neuf')
    cy.get('#amount').select('2K')
    cy.get('option').should('contain','2000 €')
    cy.get('#creditMaturity').select('M12')
    cy.get('option').should('contain','12 mois')
    cy.get('[data-di-id=di-id-bca9a80c-4fc29f73]').click()
    cy.url().should('include', '/email')
    cy.get("h2").should('contain', 'Découvrez votre offre de prêt de')
    cy.typeLogin({ email: 'michel.sapin@gmail.com'})
    cy.get('[data-test=navigator-compact-forward]').click()
})
it('Consumer choose his marital status', ()=>{
  cy.get("h2").should('contain', 'Votre situation familiale')
  cy.url().should('contain','familysituation')
  cy.get('#maritalStatus-input').select('SINGLE')
  cy.get('option').should('contain','Célibataire')
  cy.get('#childNumberPropal-input').select('0')
  cy.get('option').should('contain','0')
  cy.get('[type="checkbox"]').check({ force: true }).should('be.checked')
  cy.get('[data-test="navigator-compact-forward"]').click()
})
it('Consumer choose his housing statut',()=>{
  cy.get("h2").should('contain', 'Votre logement')
  cy.url().should('contain', '/housing')
  cy.get('#housingStatus-input').select('TENANT')
  cy.get('option').should('contain','Locataire')
  cy.wait(1000)
  cy.get('#housingStatusFrom-input-month').type('01')
  cy.get('#housingStatusFrom-input-year').type('2020')
  cy.get('[type="checkbox"]').uncheck({ force: true })
  cy.get('[data-test="navigator-compact-forward"]').click()
})

it('Consummer choose his job', () =>{
    cy.get("h2").should('contain', 'Votre situation professionnelle')
   cy.url().should('contain', '/professionalsituation')
   cy.get('#activitySector-input').select('INDEPENDENT')
   cy.get('option').should('contain','Indépendants / Travailleurs non salariés')
   cy.get('#profession-input').select('AUTO_ENTREPRENEUR')
   cy.get('option').should('contain','Auto-Entrepreneur')
   cy.get('#businessActivityStartDate-input-month').type('02')
   cy.get('#businessActivityStartDate-input-year').type('2019')
    cy.get('[data-di-id="di-id-d838032c-320c79b9"] > label').click()
   cy.get('[data-test="navigator-compact-forward"]').click()
})

it('Consumer give his salary',()=>{
  cy.get("h2").should('contain', 'Vos revenus mensuels')
  cy.url().should('contain', '/incomes')
  cy.get('#mainIncome-input').type('2000')
  cy.get('#housingAssistance-input').type('0')
  cy.get('#additionalIncome-input').type('0')
  cy.get('[data-test="navigator-compact-forward"]').click()
})

it('Consumer give his outcomes', ()=> {
  cy.get("h2").should('contain', 'Vos charges mensuelles')
  cy.url().should('contain', '/outcomes')
  cy.get('#rentAmount-input').type('500')
  cy.get('#loanCount-input').select('1')
  cy.get('option').should('contain','1')
  cy.get('#type-input').select('PERSONAL_LOAN')
  cy.get('option').should('contain','Prêt Personnel')
  cy.get('#loanAmount-input').type('20')
  cy.get('[data-test="navigator-compact-forward"]').click()
})

it ('Consumer give his Bank',()=>{
  cy.get("h2").should('contain','Votre banque')
  cy.url().should('contain', '/bank')
  cy.get('#bankCode-input').select('HSBC')
  cy.get('option').should('contain','HSBC')
  cy.get('#bankFrom-input-year').type('2010')
  cy.get('[data-test=navigator-compact-forward]').click()
})             
})  