context('Choose the options to get credit with profile3', () => {
    before(() => {
      cy.visit("https://www.younited-credit.com/")
      cy.wait(2000)
      cy.title().should('include','Le Crédit')
      cy.get('#projectSelect').select('NEWCAR')
      cy.get('option').should('contain','Véhicule neuf')
      cy.get('#amount').select('2K')
      cy.get('option').should('contain','2000 €')
      cy.get('#creditMaturity').select('M12')
      cy.get('option').should('contain','12 mois')
      cy.get('[data-di-id=di-id-bca9a80c-4fc29f73]').click()
      cy.url().should('include', '/email')
      cy.get("h2").should('contain', 'Découvrez votre offre de prêt de')
      cy.typeLogin({ email: 'michel.sapin@gmail.com'})
      cy.get('[data-test=navigator-compact-forward]').click()
  })

  it('Consummer choose his marital statut',() => {
    cy.url().should('contain','familysituation')
    cy.get("h2").should('contain', 'Votre situation familiale')
    cy.get('#maritalStatus-input').select('COHABITING')
    cy.get('option').should('contain', 'Vie Maritale / PACS')
    cy.get('#childNumberPropal-input').select('0')
    cy.get('option').should('contain','0')
    cy.get('[type="checkbox"]').check({ force: true }).should('be.checked') 
    cy.get('[data-test=navigator-compact-forward]').click()
  })
  it('Consumer choose is housing statut',()=>{
    cy.url().should('include', '/housing')
    cy.get("h2").should('contain', 'Votre logement')
    cy.get('#housingStatus-input').select('LODGING_PROVIDED_BY_PARTNER')
    cy.get('option').should('contain','Logé(e) par le(la) conjoint(e)')
    cy.wait(1000)
    cy.get('#housingStatusFrom-input-month').type('05')
    cy.get('#housingStatusFrom-input-year').type('2017')
    cy.get('[type="checkbox"]').uncheck({ force: true })
    cy.get('[data-test=navigator-compact-forward]').click()
  })
   it('Consumer choose his job',()=>{
    cy.url().should('include', '/professionalsituation')
    cy.get("h2").should('contain', 'Votre situation professionnelle')
    cy.get('#activitySector-input').select('RETIRED')
    cy.get('option').should('contain','Retraités')
    cy.get('#profession-input').select('RETIRED_FROM_PUBLIC_SECTOR')
    cy.get('option').should('contain','Retraité du secteur public')
    cy.get('#pensionFrom-input-month').type('02')
    cy.get('#pensionFrom-input-year').type('2018')
    cy.get('[data-test=navigator-compact-forward]').click()
   })
   it('Consumer choose his partner job',()=>{
    cy.url().should('include', '/partnerprofession')
    cy.get("h2").should('contain', 'Profession de votre conjoint')
    cy.get('#partnerActivitySector-input').select('PUBLIC_SECTOR')
    cy.get('option').should('contain','Salarié(e) du secteur public')
    cy.get('#partnerProfession-input').select('HOSPITAL_CAREGIVER')
    cy.get('option').should('contain','Aide soignant hospitalier')
    cy.get('#partnerContractType-input').select('CDD')
    cy.get('option').should('contain','CDD')
    cy.get('#partnerEmployedFrom-input-month').type('05')
    cy.get('#partnerEmployedFrom-input-year').type('2000')
    cy.get('[data-test=navigator-compact-forward]').click()
   })
 it('Consumer give his salary',()=>{
    cy.url().should('include', '/incomes')
    cy.get("h2").should('contain', 'Vos revenus mensuels')
    cy.get('#mainIncome-input').type('2200')
    cy.get('#coIncome-input').type('5000')
    cy.get('[data-test=navigator-compact-forward]').click()
 })
 it('Consumer give his outcomes',()=>{
    cy.url().should('include', '/outcomes')
    cy.get("h2").should('contain', 'Vos charges mensuelles')
    cy.get('#rentAmount-input').type('900')
    cy.get('#loanCount-input').select('0')
    cy.get('[data-test=navigator-compact-forward]').click()
 })   
 it('Consumer give his bank', ()=>{
    cy.url().should('include', '/bank')
    cy.get("h2").should('contain', 'Votre banque')
    cy.get('#bankCode-input').select('CREDIT_MUTUEL')
    cy.get('#bankFrom-input-year').type('1999')
    cy.get('[data-test=navigator-compact-forward]').click()
 })   
 
})